import { productsArray } from "@/productsData";
import Head from "next/head";

export default function Earphones() {
  return (
    <>
      <Head>
        <title>Audiophile | Speakers</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/assets/favicon.ico" />
      </Head>
      <main id="main--products" className="main">
        <div className="spacer-top hidden-sm-md"></div>
        <div className="spacer hidden-sm-lg"></div>
      </main>
    </>
  );
}
