import Head from "next/head";
import Navigation from "@/components/navigation/Navigation";
import Header from "@/components/header/Header";
import Shop from "@/components/shop/Shop";

export default function Home() {
  return (
    <>
      <Head>
        <title>Audiophile | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Navigation indexNav="indexNav" />
      <Header />
      <main className="main">
        <Shop />
      </main>
    </>
  );
}
