import { productsArray } from "@/productsData";
import Head from "next/head";
import Navigation from "@/components/navigation/Navigation";
import ProductHeader from "@/components/header/ProductHeader";
import ProductDetails from "@/components/product-details/ProductDetails";
import AlsoLike from "@/components/also-like/AlsoLike";
import Shop from "@/components/shop/Shop";
import About from "@/components/about/About";
import Footer from "@/components/footer/Footer";

export default function ZX7() {
  const product = productsArray[4];

  return (
    <>
      <Head>
        <title>Audiophile | ZX7 Speaker</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/assets/favicon.ico" />
      </Head>
      <Navigation />
      <ProductHeader product={product} />
      <main className="main--current-product">
        <div className="current-product-content">
          <ProductDetails product={product} />
          <AlsoLike product={product} />
        </div>
        <Shop />
        <div className="spacer hidden-sm-lg"></div>
        <About />
      </main>
      <Footer />
    </>
  );
}
